### ISSUE TITLE
irishRel:numChild ambiguity

### ISSUE THREAD

**Issue by Eystein-Thanisch** [cyocum/irish-gen#131]
Up to now, the `irishRel:numChild` predicate has been used to record the numbers of _sons_, presumably on the assumption that these are the only figures that our sources will provide. However, in Rawl_B502/_94.ttl, the number of Úgáine Mór's sons and daughters is given (22 sons, 30 daughters). Using the `irishRel:numChild` predicate would imply he had 52 sons but it would be a shame to omit the data about the daughters by only recording 22 as the datum.

Two options:

1. Record 52 children and put the text in an `rdfs:comment`.
2. Create `irishRel:numSons` and `irishRel:numDaughters` predicates.

I am easy as to which we choose :-)

**Comment by Eystein-Thanisch** [comment]
I am obviously very sympathetic to that but we should perhaps consider what sort of queries or operations are going to be performed with the data. For example, is anyone going to be using the `irishRel:numChild` data to make quantitative observations, where they wouldn't necessarily be viewing comments associated with each record?

Ok, maybe I am less easy as to which we choose.

**Comment by cyocum** [comment]
Yes, you have a point.  I am ambivalent about it.  On the one hand, we have a gender neural way and if someone really wants to differentiate, they can write a SPARQL query which will give them accurate numbers because sometimes the `numChild` is deceiving.  On the other hand, it would be good to have the distinction when it appears in the text.  I can add the predicates for the genders tonight as it will not hurt anything anyway and it is easy to do.

**Comment by Eystein-Thanisch** [comment]
As per our off-GitHub discussion, the best way forward seems to be to create new predicates (`irishRel:numSons` and `irishRel:numDaughters`) for use in cases where the text breaks down the number by gender. However, we don't need to go back and replace `irishRel:childOf`, as we can presume that that currently refers overwhelmingly, if not exclusively, to sons. This will be highlighted in any documentation for those writing queries of the data.
