### ISSUE TITLE
Representing generation counting

### ISSUE THREAD

**Issue by Eystein-Thanisch** [cyocum/irish-gen#144]
The Laud Misc 610, in its history of the Eoganachta, presents a new sort of data that might need to be represented in a triple. The text occasionally chooses an ancestor figure (_A_) and then specifies various descendants (_D_) in terms of how many generations (_n_) they are from this ancestor figure, taking the following approximate form:
> _A_, the _n_th man out from him: _D_

For example,
> Clann Núadat Decláim fodecsa .i. in sechtmad fer húadside .i. Munemón

The numbers of generations can quite large (up to 11 so far), so it would be cumbersome (although possible) to represent this with a succession of empty nodes. So could we add some sort of triple that would qualify `rel:descendantOf` with a generation count? I realise this might not be possible, as it essentially involves three objects: the ancestor URL, the descendant URL, and the generation count numeral, which would need to be linked together. Alternatively, it might be an interesting challenge.

**Comment by cyocum** [comment]
There are two plausible options and one I would really rather avoid if at all possible.  The first option is we would need to create a new predicate with something like `irishRel:numGenerationsFrom` which would then have the generation count.  The second option, which you already identified, the blank node is clunky but I think the blank node approach may be the best.  This is because you can put `owl:sameAs` in the blank node when you can tell that a missing generation would align with a known person in the same position in another MS.  The last and unpalatable option is called [RDF reification](http://patterns.dataincubator.org/book/reified-statement.html) which is how you augment a triple or talk about a triple as a whole unit.  It is also known as "RDF's Big Ugly" and I would really rather avoid it.

Let me know which option you would prefer.  I am not attached to either of the two plausible options but I really do not want to get into reification.

**Comment by Eystein-Thanisch** [comment]
Maybe we should go with blank nodes, in that case. My problem with Option 1 is that a URI might theoretically be the subject of more than one `rel:descendantOf` predicate, which would create confusion as to which the generation count referred to.

As you say, linking the blank nodes to pedigrees is a very attractive added advantage. Annoyingly, in the examples I am looking at, the generation counts usually don't match pedigrees in other sources. But it would work well if they did! 

One caveat, however: we'd need to link the blank nodes to all versions of the intervening pedigree, if they differ, as we will usually have no way of knowing which one the gene

**Comment by Eystein-Thanisch** [comment]
Sorry! Writing from my phone and my thumb slipped...

**Comment by cyocum** [comment]
OK, blank nodes it is.  You may want to put a comment in the file with a link to this discussion so if someone looks they will be linked back here.  Yes, it does have its drawbacks and it is rather clunky but it seems better than the alternatives at the moment.
