### ISSUE TITLE
typo in the propertychain rel:siblingOf

### ISSUE THREAD

**Issue by gatemezing** [cyocum/irish-gen#191]
Hello,
Looking at the ontology `earlyIrishRelationship.ttl` the following relation seems to have a typo in owl:TransitiveProperty. Altough the turtle file is correct, the semantics is not what you wanted to express?!

```
rel:siblingOf
    a owl:TransitivePoperty, owl:SymmetricProperty;
    owl:propertyChainAxiom (rel:childOf [owl:inverseOf rel:childOf]).
```
This makes the relation `rel:siblingOf` an instance of the class `owl:TransitivePoperty`[See Protege view](https://www.dropbox.com/s/i2o3o0n1b6zad7o/Capture%20d%27%C3%A9cran%202018-12-12%2010.37.55.png?dl=0). 

HTH.

**Comment by cyocum** [comment]
Thanks for picking up the typo! I am not sure how it got past me.  I believe that you want siblingOf to be transitive because the brother of my brother is also my brother. I originally got this from the Advanced OWL tutorial from Manchester University (http://mowl-power.cs.man.ac.uk/fhkbtutorial/resources/FHKB-tutorial_v1_0.pdf).  I may have misunderstood or mistranslated it though so please have a look and let me know.

**Comment by Eystein-Thanisch** [comment]
Not sure how I missed it either. I suppose we don't explicitly input that people are siblings very often so won't have looked at it much. Anyway, it's fixed now. Thanks a lot @gatemezing !
